import type { Logger } from 'winston'

import { buildGenerationPrompts } from '../../llm/prompts/generation.prompts'
import { getProvider } from '../../llm/providers/registry'
import { logger } from '../../logger'
import type { ContextRetriever } from '../rag/retriever'
import type { ContextBuilder, FileContext } from './context-builder'
import type { DependencyGraph } from './dependency-analyzer'
import { ImportRegistry } from './import-registry'
import type { IntentSchema } from './intent-analyzer'
import type { Relationship } from './schema-validator'
import type { TaskPlan } from './task-planner'

export interface GeneratedFile {
  path: string
  content: string
}

export interface FileGeneratorOptions {
  /** Project ID used to retrieve existing files from the RAG store. */
  projectId?: string
  /**
   * If provided, each file task retrieves up to 3 semantically relevant existing
   * project files before generation, giving the model cross-file context.
   */
  retriever?: ContextRetriever
  /** Optional project memory block injected into every generation prompt. */
  memoryBlock?: string
  /** Validated relationships between entities for proper foreign key implementation */
  relationships?: Relationship[]
  /** Pre-built global context for all files */
  globalContext?: Map<string, FileContext>
  /** Dependency graph for the project */
  dependencyGraph?: DependencyGraph
  /** Context builder for generating context blocks */
  contextBuilder?: ContextBuilder
  /**
   * Full ordered task plan for all project files.
   * Injected into every prompt as a manifest so generators know the complete
   * file list and avoid inventing imports that don't exist.
   */
  plan?: TaskPlan[]
  /**
   * Files already generated by the template engine (scaffold stage).
   * These skip LLM generation entirely — content is used as-is.
   */
  preScaffolded?: Map<string, string>
  /** Optional stage logger for debug output to file logs. */
  log?: Logger
}

export class FileGenerator {
  private importRegistry = new ImportRegistry()

  /**
   * Generates all files with dependency-aware context.
   *
   * Pre-scaffolded files (from the template engine) are used as-is and registered
   * into the import registry so subsequent LLM calls receive exact import hints.
   *
   * LLM generation runs in topological stage order; within each stage, files that
   * are single-GPU-safe run sequentially (parallelism=1 for stages that use the LLM).
   */
  async generateAll(
    prompt: string,
    schema: IntentSchema,
    plan: TaskPlan[],
    onProgress: (index: number, total: number, path: string) => Promise<void>,
    options: FileGeneratorOptions = {}
  ): Promise<GeneratedFile[]> {
    const preScaffolded = options.preScaffolded ?? new Map<string, string>()
    const log = options.log ?? logger

    // Reset registry for each generation run
    this.importRegistry = new ImportRegistry()

    // Pre-register all scaffold files so LLM stages can see their symbols
    for (const [path, content] of preScaffolded) {
      this.importRegistry.register(path, content)
    }

    const indexedPlan = plan.map((task, index) => ({ task, index, stage: classifyTaskStage(task.path) }))
    const totalStages = Math.max(0, ...indexedPlan.map(item => item.stage)) + 1
    const generatedByIndex = new Map<number, GeneratedFile>()

    // Seed generatedByIndex with scaffold files so dependency context is available
    for (const { task, index } of indexedPlan) {
      const scaffolded = preScaffolded.get(task.path)
      if (scaffolded !== undefined) {
        generatedByIndex.set(index, { path: task.path, content: scaffolded })
      }
    }

    let startedCount = 0

    for (let stage = 0; stage < totalStages; stage++) {
      const stageTasks = indexedPlan
        .filter(item => item.stage === stage)
        .sort((a, b) => a.index - b.index)

      if (stageTasks.length === 0) continue

      // Separate tasks already covered by scaffold from tasks that need LLM
      const llmTasks = stageTasks.filter(item => !preScaffolded.has(item.task.path))
      const scaffoldTasks = stageTasks.filter(item => preScaffolded.has(item.task.path))

      // Emit progress events for scaffold tasks (they're already generated)
      for (const { task } of scaffoldTasks) {
        const progressIndex = startedCount++
        await onProgress(progressIndex, plan.length, task.path)
        log.info('FileGenerator: scaffold (template) %s (%d/%d)', task.path, progressIndex + 1, plan.length)
      }

      if (llmTasks.length === 0) continue

      log.info(
        'FileGenerator: stage %d — %d LLM files (parallelism=%d)',
        stage,
        llmTasks.length,
        parallelismForStage(stage)
      )

      let nextTaskCursor = 0
      const workerCount = Math.min(parallelismForStage(stage), llmTasks.length)
      const stageWorkers = Array.from({ length: workerCount }, async () => {
        while (true) {
          const cursor = nextTaskCursor
          nextTaskCursor += 1
          if (cursor >= llmTasks.length) break

          const { task, index } = llmTasks[cursor]
          const progressIndex = startedCount++
          const fileStartedAt = Date.now()

          await onProgress(progressIndex, plan.length, task.path)

          // Fast path: __init__.py stubs (no LLM call needed)
          if (task.path.endsWith('__init__.py')) {
            const content = generateInitPyStub(task.path, options.plan ?? [])
            generatedByIndex.set(index, { path: task.path, content })
            this.importRegistry.register(task.path, content)
            log.info('FileGenerator: __init__.py stub %s (fast path, %dms)', task.path, Date.now() - fileStartedAt)
            continue
          }

          // Build context including import hints from already-generated files
          const generationContext = await this.buildGenerationContext(task, generatedByIndex, options)

          const content = await this.generateOne(prompt, schema, task, generationContext, log)

          generatedByIndex.set(index, { path: task.path, content })
          this.importRegistry.register(task.path, content)

          log.info(
            'FileGenerator: LLM generated %s in %dms (%d/%d)',
            task.path,
            Date.now() - fileStartedAt,
            progressIndex + 1,
            plan.length
          )
        }
      })

      await Promise.all(stageWorkers)
      log.info('FileGenerator: completed stage %d', stage)
    }

    return [...generatedByIndex.entries()].sort((a, b) => a[0] - b[0]).map(([, file]) => file)
  }

  /**
   * Builds comprehensive generation context for a file.
   * Combines dependency context, RAG context, memory, architecture hints,
   * a full project manifest, and exact import hints from the import registry.
   */
  private async buildGenerationContext(
    task: TaskPlan,
    generatedFiles: Map<number, GeneratedFile>,
    options: FileGeneratorOptions
  ): Promise<{
    dependencies: GeneratedFile[]
    existingFiles: { path: string; content: string }[]
    memoryBlock?: string
    contextBlock?: string
    relationships?: Relationship[]
    projectManifest?: string
    availableImports?: string
  }> {
    // Get dependency context (all files this file depends on)
    const dependencyPaths = options.dependencyGraph?.nodes.get(task.path)?.dependencies ?? []
    const dependencies = dependencyPaths
      .map(path => {
        const generatedFile = Array.from(generatedFiles.values()).find(f => f.path === path)
        return generatedFile ? { path, content: generatedFile.content } : null
      })
      .filter((f): f is { path: string; content: string } => f !== null)

    // Fetch semantically relevant existing project files (RAG)
    let existingFiles: { path: string; content: string }[] = []
    if (options.retriever && options.projectId) {
      try {
        existingFiles = await options.retriever.getRelevantFiles(
          options.projectId,
          `${task.path}: ${task.description}`,
          3
        )
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err)
        ;(options.log ?? logger).warn('FileGenerator: RAG retrieval failed for %s: %s', task.path, msg)
      }
    }

    // Get context block for this file (dependency API surface + relationships)
    let contextBlock: string | undefined
    if (options.globalContext && options.contextBuilder) {
      const fileContext = options.globalContext.get(task.path)
      if (fileContext) {
        contextBlock = options.contextBuilder.getContextBlock(fileContext, options.globalContext)
      }
    }

    // Build compact project manifest
    const projectManifest = options.plan ? buildProjectManifest(options.plan, options.globalContext) : undefined

    // Build exact import hints from all already-generated dependency files
    const availableImports = dependencyPaths.length > 0
      ? this.importRegistry.getAvailableImports(dependencyPaths)
      : undefined

    return {
      dependencies,
      existingFiles,
      memoryBlock: options.memoryBlock,
      contextBlock,
      relationships: options.relationships,
      projectManifest,
      availableImports: availableImports || undefined
    }
  }

  private async generateOne(
    prompt: string,
    schema: IntentSchema,
    task: TaskPlan,
    context: {
      dependencies: GeneratedFile[]
      existingFiles: { path: string; content: string }[]
      memoryBlock?: string
      contextBlock?: string
      relationships?: Relationship[]
      projectManifest?: string
      availableImports?: string
    },
    log: Logger = logger
  ): Promise<string> {
    const provider = getProvider()
    const maxAttempts = 4
    const retryDelays = [1000, 2000, 4000] // Progressive delay: 1s, 2s, 4s

    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      const attemptStartedAt = Date.now()
      try {
        let raw = ''
        const systemPrompt = buildGenerationPrompts.generateFileSystemPrompt(task.path)
        const userPrompt = buildGenerationPrompts.generateFileUserPrompt(
          prompt,
          schema,
          task,
          context.dependencies,
          context.existingFiles,
          context.memoryBlock,
          context.relationships,
          context.contextBlock,
          context.projectManifest,
          context.availableImports
        )
        log.debug('FileGenerator: LLM call for %s — system=%d chars, user=%d chars', task.path, systemPrompt.length, userPrompt.length)

        for await (const chunk of provider.chatStream(
          [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userPrompt }
          ],
          undefined,
          {
            temperature: 0.1,
            num_ctx: contextWindowForPath(task.path),
            num_predict: tokenBudgetForPath(task.path)
          }
        )) {
          raw += chunk.message.content
        }

        const clean = stripFences(raw)
        if (!clean) throw new Error('Generated file content is empty')
        log.debug(
          'FileGenerator: attempt %d/%d succeeded for %s in %dms (%d chars)',
          attempt,
          maxAttempts,
          task.path,
          Date.now() - attemptStartedAt,
          clean.length
        )
        return clean
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err)
        log.warn(
          'FileGenerator: attempt %d/%d failed for %s after %dms: %s',
          attempt,
          maxAttempts,
          task.path,
          Date.now() - attemptStartedAt,
          msg
        )

        if (attempt < maxAttempts) {
          // Add progressive delay before retry
          const delay = retryDelays[attempt - 1] || 1000
          log.debug('FileGenerator: waiting %dms before retry', delay)
          await new Promise(resolve => setTimeout(resolve, delay))
        } else {
          throw new Error(
            `FileGenerator: failed to generate ${task.path} after ${maxAttempts} attempts: ${msg}`
          )
        }
      }
    }

    // Unreachable, but satisfies TypeScript
    throw new Error('FileGenerator: unexpected exit')
  }
}

function classifyTaskStage(path: string): number {
  const normalized = path.toLowerCase()

  if (
    normalized === 'requirements.txt' ||
    normalized === '.env' ||
    normalized === '.env.example' ||
    normalized === 'alembic.ini' ||
    normalized.startsWith('app/core/')
  ) {
    return 0
  }

  if (normalized.startsWith('app/models/')) {
    return 1
  }

  if (normalized.startsWith('app/schemas/')) {
    return 2
  }

  if (normalized.startsWith('app/services/') || normalized.startsWith('app/utils/')) {
    return 3
  }

  if (normalized.startsWith('app/api/')) {
    return 4
  }

  if (normalized === 'main.py' || normalized.startsWith('app/__')) {
    return 5
  }

  if (normalized.startsWith('tests/') || normalized.startsWith('docs/') || normalized === 'readme.md') {
    return 6
  }

  return 5
}

function truncateForContext(content: string, maxChars: number): string {
  if (content.length <= maxChars) {
    return content
  }

  const head = Math.floor(maxChars * 0.7)
  const tail = Math.floor(maxChars * 0.3)

  return `${content.slice(0, head)}\n\n... [truncated for context budget] ...\n\n${content.slice(
    Math.max(0, content.length - tail)
  )}`
}

// Single-GPU constraint: never run LLM calls in parallel
function parallelismForStage(_stage: number): number {
  return 1
}

function tokenBudgetForPath(path: string): number {
  const normalized = path.toLowerCase()

  if (normalized.endsWith('__init__.py')) {
    return 512
  }

  if (normalized.startsWith('app/models/') || normalized.startsWith('app/services/')) {
    return 6400
  }

  if (normalized.startsWith('app/api/') || normalized.startsWith('app/schemas/')) {
    return 5200
  }

  if (normalized === 'requirements.txt' || normalized === 'readme.md' || normalized.startsWith('docs/')) {
    return 2400
  }

  if (normalized.startsWith('tests/')) {
    return 4400
  }

  return 4800
}

function contextWindowForPath(path: string): number {
  const normalized = path.toLowerCase()

  if (normalized.endsWith('__init__.py')) {
    return 4096
  }

  // Use full configured context window for all other files
  return 32768
}

function stripFences(text: string): string {
  const trimmed = text.trim()
  // Match optional leading whitespace/newlines before opening fence, and after closing fence
  const fenced = trimmed.match(/^```[\w]*\r?\n([\s\S]*?)\n?```\s*$/)
  if (fenced) {
    return fenced[1].trim()
  }
  return trimmed
}

/**
 * Generates a static stub for a Python __init__.py file.
 * Avoids calling the LLM for trivial package init files.
 * For model/schema/service packages, generates re-export lines from siblings in the plan.
 */
function generateInitPyStub(_initPath: string, _plan: TaskPlan[]): string {
  return '# Package initialization\n'
}

/**
 * Builds a compact project manifest string listing every planned file's path,
 * one-line description, and expected exports (derived from the global context).
 * Injected into every generation prompt so the LLM knows about the full project
 * without having to see every file's content — keeps token cost low.
 *
 * Format:
 *   app/models/user.py — SQLAlchemy model for User  [exports: User]
 *   app/schemas/user.py — Pydantic schemas for User  [exports: UserBase, UserCreate, UserUpdate, UserResponse]
 *   ...
 */
function buildProjectManifest(
  plan: TaskPlan[],
  globalContext?: Map<string, import('./context-builder').FileContext>
): string {
  const lines: string[] = ['PROJECT FILE MANIFEST (all files in this project):']

  for (const task of plan) {
    const ctx = globalContext?.get(task.path)
    const exportsStr =
      ctx && ctx.exportsProvided.length > 0 ? `  [exports: ${ctx.exportsProvided.join(', ')}]` : ''
    lines.push(`  ${task.path} — ${task.description}${exportsStr}`)
  }

  lines.push(
    '',
    'CRITICAL: When importing from any file in this manifest, use ONLY the names listed in its [exports] annotation.',
    'Do NOT invent class or function names that are not in the manifest.'
  )

  return lines.join('\n')
}
