import { createHash } from 'crypto'

import { BaseAgent } from '../framework/base-agent'
import { ContextRetriever } from '../rag/retriever'
import type { GeneratedFile, PipelineContext } from '../types'
import { validateGeneratedFiles } from '../validation/validator'

const STEP_BASELINE_FILES: Record<
  'create_db_schema' | 'generate_services' | 'generate_routes' | 'generate_validation' | 'generate_tests',
  Record<'fast-api' | 'feathers', GeneratedFile[]>
> = {
  create_db_schema: {
    'fast-api': [
      {
        path: 'app/models/base.py',
        content:
          'from pydantic import BaseModel\n\n\nclass APIModel(BaseModel):\n    class Config:\n        from_attributes = True\n'
      },
      {
        path: 'app/schemas/common.py',
        content: 'from pydantic import BaseModel\n\n\nclass HealthResponse(BaseModel):\n    status: str\n'
      }
    ],
    feathers: [
      {
        path: 'src/models/index.ts',
        content: 'export type EntityId = string\n'
      },
      {
        path: 'src/schema/common.ts',
        content: 'export interface HealthResponse {\n  status: string\n}\n'
      }
    ]
  },
  generate_services: {
    'fast-api': [
      {
        path: 'app/services/health_service.py',
        content:
          "class HealthService:\n    @staticmethod\n    async def get_health() -> dict[str, str]:\n        return {'status': 'ok'}\n"
      }
    ],
    feathers: [
      {
        path: 'src/services/health/health.class.ts',
        content: 'export class HealthService {\n  async find() {\n    return { status: \"ok\" }\n  }\n}\n'
      }
    ]
  },
  generate_routes: {
    'fast-api': [
      {
        path: 'app/routes/health.py',
        content:
          "from fastapi import APIRouter\nfrom app.services.health_service import HealthService\n\nrouter = APIRouter(prefix='/health', tags=['health'])\n\n@router.get('')\nasync def health_check():\n    return await HealthService.get_health()\n"
      }
    ],
    feathers: [
      {
        path: 'src/services/health/health.routes.ts',
        content:
          "import type { Application } from '../../declarations'\nimport { HealthService } from './health.class'\n\nexport const healthPath = 'health'\n\nexport const health = (app: Application) => {\n  app.use(healthPath, new HealthService())\n}\n"
      }
    ]
  },
  generate_validation: {
    'fast-api': [
      {
        path: 'app/schemas/validators.py',
        content:
          'from pydantic import BaseModel, Field\n\n\nclass PaginationQuery(BaseModel):\n    limit: int = Field(default=20, ge=1, le=100)\n    offset: int = Field(default=0, ge=0)\n'
      }
    ],
    feathers: [
      {
        path: 'src/schema/validators.ts',
        content:
          'export const validatePagination = (limit = 20, offset = 0) => ({\n  limit: Math.max(1, Math.min(limit, 100)),\n  offset: Math.max(0, offset)\n})\n'
      }
    ]
  },
  generate_tests: {
    'fast-api': [
      {
        path: 'tests/test_health.py',
        content:
          "from app.services.health_service import HealthService\n\n\nasync def test_health_service_returns_ok():\n    result = await HealthService.get_health()\n    assert result['status'] == 'ok'\n"
      }
    ],
    feathers: [
      {
        path: 'test/health.service.test.ts',
        content:
          "import { describe, it, expect } from 'vitest'\nimport { HealthService } from '../src/services/health/health.class'\n\ndescribe('HealthService', () => {\n  it('returns ok status', async () => {\n    const service = new HealthService()\n    await expect(service.find()).resolves.toMatchObject({ status: 'ok' })\n  })\n})\n"
      }
    ]
  }
}

function fallbackFiles(
  context: PipelineContext,
  targetStep:
    | 'create_db_schema'
    | 'generate_services'
    | 'generate_routes'
    | 'generate_validation'
    | 'generate_tests'
): GeneratedFile[] {
  const baseName = context.projectId.slice(0, 8)
  const framework = context.framework
  const baseline = STEP_BASELINE_FILES[targetStep]?.[framework] || []

  if (framework === 'fast-api') {
    return [
      ...baseline,
      {
        path: 'requirements.txt',
        content: 'fastapi\nuvicorn[standard]\npydantic\n'
      },
      {
        path: 'main.py',
        content:
          "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get('/health')\nasync def health():\n    return {'status': 'ok'}\n"
      },
      {
        path: 'README.md',
        content: `# Generated FastAPI Backend ${baseName}\n\nThis backend was generated by Mockline agentic workflow.\n`
      }
    ]
  }

  return [
    ...baseline,
    {
      path: 'README.md',
      content: `# Generated Feathers Backend ${baseName}\n\nThis backend was generated by Mockline agentic workflow.\n`
    },
    {
      path: 'src/main.ts',
      content: "export const health = () => ({ status: 'ok' })\n"
    },
    {
      path: 'src/routes/health.ts',
      content: "export const healthRoute = { method: 'GET', path: '/health' }\n"
    }
  ]
}

export class CodeGenerationAgent extends BaseAgent {
  constructor(
    app: any,
    private readonly targetStep:
      | 'create_db_schema'
      | 'generate_services'
      | 'generate_routes'
      | 'generate_validation'
      | 'generate_tests'
  ) {
    super(app, targetStep)
  }

  protected async execute(context: PipelineContext) {
    const retriever = new ContextRetriever(this.app)
    const retrieved = await retriever.getRelevantFiles(
      context.projectId,
      `${context.prompt}\n${this.targetStep}`,
      6
    )

    const retrievalSection = retrieved.length
      ? [
          'Relevant project context:',
          ...retrieved.map(file => {
            const snippet = file.content.slice(0, 1200)
            return [`FILE: ${file.path}`, '```', snippet, '```'].join('\n')
          })
        ].join('\n\n')
      : 'Relevant project context: none found'

    const stackInstruction =
      context.framework === 'feathers'
        ? 'Target FeathersJS v5 + TypeScript conventions, service registration, and app hooks.'
        : 'Target FastAPI + Python conventions, pydantic schemas, and uvicorn entrypoint.'

    const requestedAreas = this.detectRequestedAreas(context.prompt)
    const mustCover = requestedAreas.length > 0 ? requestedAreas.join(', ') : 'core backend API structure'

    const generatedText = await this.generateStructuredText(
      'generate_backend_code',
      [
        `Generate production-oriented code artifacts for step: ${this.targetStep}.`,
        stackInstruction,
        `Requested focus areas from user prompt: ${mustCover}.`,
        `For this step, generate complete implementation files with professional structure, explicit error handling, and clean naming.`,
        `Do not return placeholders like TODO or "implement later".`,
        `Output format (strict):`,
        `FILE: path/to/file.ext`,
        '```language',
        '...full code...',
        '```'
      ].join('\n'),
      context,
      {
        role: 'generator',
        extraSections: [retrievalSection]
      }
    )

    const reflectedText = await this.generateStructuredText(
      'generate_backend_code',
      [
        'Review and improve the generated file set before code review.',
        'Preserve good sections, fix weak parts, and keep strict FILE blocks format.',
        'Output only final FILE blocks.'
      ].join('\n'),
      context,
      {
        role: 'reflection',
        extraSections: ['Candidate output to refine:', '```', generatedText, '```']
      }
    )

    const criticReport = await this.generateStructuredText(
      'small_edits',
      [
        'Critique the candidate output for architecture violations, duplicated logic, missing imports, and security flaws.',
        'Respond in JSON only with shape:',
        '{"approved": boolean, "issues": string[]}'
      ].join('\n'),
      context,
      {
        role: 'critic',
        extraSections: ['Candidate output:', '```', reflectedText, '```']
      }
    )

    const critic = this.parseCriticReport(criticReport)

    const candidateAfterCritic =
      !critic.approved && critic.issues.length > 0
        ? await this.generateStructuredText(
            'debugging',
            [
              'Fix the candidate output using the critic feedback.',
              'Resolve all listed issues while keeping strict FILE blocks format.',
              'Output only final FILE blocks.'
            ].join('\n'),
            context,
            {
              role: 'fixer',
              extraSections: [
                `Critic issues:\n${critic.issues.map((issue, index) => `${index + 1}. ${issue}`).join('\n')}`,
                'Candidate output to fix:',
                '```',
                reflectedText,
                '```'
              ]
            }
          )
        : reflectedText

    const loopGuardWarning = this.detectPatchLoopWarning(context, candidateAfterCritic)

    let parsed = this.parseGeneratedFiles(candidateAfterCritic)

    let sandbox = await validateGeneratedFiles(parsed, context.projectId, this.app)

    if (sandbox.failCount > 0 && parsed.length > 0) {
      const fixedForSandbox = await this.generateStructuredText(
        'debugging',
        [
          'Fix syntax and structural issues discovered by sandbox validation.',
          'Output only final FILE blocks.'
        ].join('\n'),
        context,
        {
          role: 'fixer',
          extraSections: [
            `Sandbox validation errors:\n${this.stringifyValidationErrors(sandbox)}`,
            'Candidate output to fix:',
            '```',
            candidateAfterCritic,
            '```'
          ]
        }
      )

      const sandboxParsed = this.parseGeneratedFiles(fixedForSandbox)
      if (sandboxParsed.length > 0) {
        parsed = sandboxParsed
        sandbox = await validateGeneratedFiles(parsed, context.projectId, this.app)
      }
    }

    const usedFallback = parsed.length === 0
    const files = usedFallback ? fallbackFiles(context, this.targetStep) : parsed
    const warnings = [...context.warnings]

    if (loopGuardWarning) warnings.push(loopGuardWarning)
    if (sandbox.failCount > 0) {
      warnings.push(`Sandbox validation reported ${sandbox.failCount} file(s) with issues`)
    }

    const metadata = {
      ...context.metadata,
      [`${this.targetStep}_stats`]: {
        generatedFiles: files.length,
        parsedFiles: parsed.length,
        usedFallback,
        retrievedFiles: retrieved.length,
        criticApproved: critic.approved,
        criticIssueCount: critic.issues.length,
        sandboxFailures: sandbox.failCount,
        timestamp: Date.now()
      },
      patchSignatures: this.pushPatchSignature(context, files)
    }

    return {
      context: {
        ...context,
        files: this.mergeFiles(context.files, files),
        metadata,
        warnings
      },
      summary: `${this.targetStep} generated ${files.length} file artifacts${usedFallback ? ' (fallback)' : ''}`
    }
  }

  private parseCriticReport(report: string): { approved: boolean; issues: string[] } {
    const jsonMatch = report.match(/\{[\s\S]*\}/)
    if (!jsonMatch) {
      return { approved: false, issues: ['Critic returned non-JSON feedback'] }
    }

    try {
      const parsed = JSON.parse(jsonMatch[0]) as { approved?: boolean; issues?: unknown[] }
      const issues = Array.isArray(parsed.issues)
        ? parsed.issues.map(item => String(item).trim()).filter(Boolean)
        : []

      return {
        approved: Boolean(parsed.approved),
        issues
      }
    } catch {
      return { approved: false, issues: ['Critic JSON could not be parsed'] }
    }
  }

  private stringifyValidationErrors(validation: Awaited<ReturnType<typeof validateGeneratedFiles>>): string {
    return validation.results
      .filter(result => !result.valid)
      .map(result => `${result.path}: ${result.errors.join('; ')}`)
      .join('\n')
  }

  private pushPatchSignature(context: PipelineContext, files: GeneratedFile[]): string[] {
    const existing = Array.isArray((context.metadata as any)?.patchSignatures)
      ? ((context.metadata as any).patchSignatures as string[])
      : []

    const normalized = files
      .slice()
      .sort((left, right) => left.path.localeCompare(right.path))
      .map(file => `${file.path}\n${file.content}`)
      .join('\n\n')

    const signature = createHash('sha1').update(normalized).digest('hex')
    return [...existing.slice(-4), signature]
  }

  private detectPatchLoopWarning(context: PipelineContext, candidateText: string): string | null {
    const existing = Array.isArray((context.metadata as any)?.patchSignatures)
      ? ((context.metadata as any).patchSignatures as string[])
      : []

    const signature = createHash('sha1').update(candidateText).digest('hex')
    const recent = [...existing.slice(-2), signature]
    const allSame = recent.length === 3 && recent.every(item => item === signature)

    return allSame
      ? `Loop guard triggered on ${this.targetStep}: identical patch candidate repeated 3 times`
      : null
  }

  private parseGeneratedFiles(text: string): GeneratedFile[] {
    const files: GeneratedFile[] = []
    const seenPaths = new Set<string>()

    const patterns = [
      /FILE:\s*([^\n`]+)\n\s*```[\w\-.]*\n([\s\S]*?)\n\s*```/g,
      /FILE:\s*([^\n`]+)\s*```[\w\-.]*\n([\s\S]*?)\n\s*```/g,
      /###\s*File:\s*([^\n`]+)\n\s*```[\w\-.]*\n([\s\S]*?)\n\s*```/g
    ]

    for (const fileRegex of patterns) {
      let match: RegExpExecArray | null

      while ((match = fileRegex.exec(text)) !== null) {
        const path = match[1]?.trim()
        const content = match[2]?.trim()
        if (!path || !content || seenPaths.has(path)) continue
        seenPaths.add(path)
        files.push({ path, content })
      }
    }

    return files
  }

  private detectRequestedAreas(prompt: string): string[] {
    const content = prompt.toLowerCase()
    const areas = [
      ['authentication', ['auth', 'jwt', 'oauth', 'login', 'signup']],
      ['database', ['database', 'postgres', 'mysql', 'sqlite', 'mongo', 'model']],
      ['validation', ['validation', 'validator', 'schema']],
      ['testing', ['test', 'testing', 'spec']],
      ['background processing', ['queue', 'worker', 'job', 'cron']],
      ['file uploads', ['upload', 'file', 'storage', 's3', 'r2']],
      ['realtime', ['socket', 'websocket', 'realtime']]
    ] as const

    return areas
      .filter(([, keywords]) => keywords.some(keyword => content.includes(keyword)))
      .map(([label]) => label)
  }

  private mergeFiles(existing: GeneratedFile[], incoming: GeneratedFile[]): GeneratedFile[] {
    const map = new Map<string, GeneratedFile>()
    for (const item of existing) map.set(item.path, item)
    for (const item of incoming) map.set(item.path, item)
    return Array.from(map.values())
  }
}
